PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

DELETE {
  ?s ?p ?o
}
where {
  {
    ?s ?p ?o .
    FILTER(?p NOT IN (rdf:type, skos:prefLabel))
  }
  UNION
  {
    BIND(skos:prefLabel as ?p)
    ?s ?p ?o .
    FILTER(LANG(?o) != 'en')
  }
}
